// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDSakVN1T5jwhtkkLoU-AF8p0PDixLTM',
    appId: '1:238837884180:web:8312a24d35b091dda38e01',
    messagingSenderId: '238837884180',
    projectId: 'carrental000',
    authDomain: 'carrental000.firebaseapp.com',
    storageBucket: 'carrental000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBEkdOfTjYRqE1mwfkInOo006TTeQLHOw',
    appId: '1:238837884180:android:fc66474c33899482a38e01',
    messagingSenderId: '238837884180',
    projectId: 'carrental000',
    storageBucket: 'carrental000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnLEz9J_cyRu0MB9_HVRPsbtt1UbtYjgE',
    appId: '1:238837884180:ios:fd2f89559827b26da38e01',
    messagingSenderId: '238837884180',
    projectId: 'carrental000',
    storageBucket: 'carrental000.appspot.com',
    iosBundleId: 'com.sobgog.carRental',
  );

}